/* Generated by vala-dbus-binding-tool 1.0-aa2fb. Do not modify! */
/* Generated with: vala-dbus-binding-tool --api-path=./org.freedesktop.portal.Request.xml --directory=./ --strip-namespace=org --rename-namespace=freedesktop:Freedesktop --rename-namespace=portal:Portal --no-synced */
using GLib;

namespace Freedesktop {

	namespace Portal {

		[DBus (name = "org.freedesktop.portal.Request", timeout = 120000)]
		public interface Request : GLib.Object {

			[DBus (name = "Close")]
			public abstract void close() throws DBusError, IOError;

			[DBus (name = "Response")]
			public signal void response(uint response, GLib.HashTable<string, GLib.Variant> results);
		}
	}
}
