/* Generated by vala-dbus-binding-tool 1.0-aa2fb. Do not modify! */
/* Generated with: vala-dbus-binding-tool --api-path=./org.freedesktop.portal.Session.xml --directory=./ --strip-namespace=org --rename-namespace=freedesktop:Freedesktop --rename-namespace=portal:Portal --no-synced */
using GLib;

namespace Freedesktop {

	namespace Portal {

		[DBus (name = "org.freedesktop.portal.Session", timeout = 120000)]
		public interface Session : GLib.Object {

			[DBus (name = "Close")]
			public abstract void close() throws DBusError, IOError;

			[DBus (name = "Closed")]
			public signal void closed(GLib.HashTable<string, GLib.Variant> details);

			[DBus (name = "version")]
			public abstract uint version {  get; }
		}
	}
}
